name: James_Schauf
favicon: null
layout_spectrum: 0.14868565718643367
typography_spectrum: 0.8944058446213603
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.301573928212747
  lightness: 0.6451800388749689
  saturation: 0.3142161669675261
  rhythmicContrast: 0.7206616320181638
purpose: []
