name: James_Schauf
favicon: null
layout_spectrum: 1
typography_spectrum: 0.13473
title: Dreaming in Pixels
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f6f7'
    - '#000a14'
    - '#6691a1'
    - '#01596d'
    - '#c36101'
  brandStrength: 0.25
  lightness: 0.4375
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
